name       : dmg2img
version    : 1.6.7
release    : 2
source     :
    - http://vu1tur.eu.org/tools/dmg2img-1.6.7.tar.gz : 02aea6d05c5b810074913b954296ddffaa43497ed720ac0a671da4791ec4d018
license    : GPL-2.0-or-later
component  : system.utils
summary    : Program that lets you convert .dmg files to .img files
description: |
    DMG2IMG is a tool which allows converting Apple compressed dmg archives to standard (hfsplus) image disk files. Just go to the folder where the .dmg file is located cd PATH/TO/THE/FILE and then convert it by doing dmg2img NAMEOFTHEFILE.dmg NAMEOFTHEFILE.img
builddeps  :
    - bzip2-devel
build      : |
    %make
install    : |
    %make_install
